# Generated by Django 5.2.8 on 2025-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
