# Generated by Django 5.2.8 on 2025-12-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_record', to='habits.habit')),
            ],
        ),
    ]
